server:
  port: 9898
spring:
  application:
    name: infrr-poc
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 1024MB
      max-request-size: 1024MB

logging:
  config: classpath:log/log4j2.xml
file:
  upload-dir: /naveen/uploads



